/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Adriyan
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    
    double n1, n2, result;
    String operator;
    
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_text = new javax.swing.JTextField();
        c_btn = new javax.swing.JButton();
        i4_btn = new javax.swing.JButton();
        i7_btn = new javax.swing.JButton();
        i1_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        i5_btn = new javax.swing.JButton();
        i8_btn = new javax.swing.JButton();
        i2_btn = new javax.swing.JButton();
        i9_btn = new javax.swing.JButton();
        i3_btn = new javax.swing.JButton();
        per_btn = new javax.swing.JButton();
        i6_btn = new javax.swing.JButton();
        dev_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        mul_btn = new javax.swing.JButton();
        point_btn = new javax.swing.JButton();
        ans_btn = new javax.swing.JButton();
        i0_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        c_btn.setText("C");
        c_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_btnActionPerformed(evt);
            }
        });

        i4_btn.setText("4");
        i4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i4_btnActionPerformed(evt);
            }
        });

        i7_btn.setText("7");
        i7_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i7_btnActionPerformed(evt);
            }
        });

        i1_btn.setText("1");
        i1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        i5_btn.setText("5");
        i5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i5_btnActionPerformed(evt);
            }
        });

        i8_btn.setText("8");
        i8_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i8_btnActionPerformed(evt);
            }
        });

        i2_btn.setText("2");
        i2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2_btnActionPerformed(evt);
            }
        });

        i9_btn.setText("9");
        i9_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i9_btnActionPerformed(evt);
            }
        });

        i3_btn.setText("3");
        i3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3_btnActionPerformed(evt);
            }
        });

        per_btn.setText("%");
        per_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                per_btnActionPerformed(evt);
            }
        });

        i6_btn.setText("6");
        i6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i6_btnActionPerformed(evt);
            }
        });

        dev_btn.setText("/");
        dev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dev_btnActionPerformed(evt);
            }
        });

        add_btn.setText("+");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        sub_btn.setText("-");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });

        mul_btn.setText("X");
        mul_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul_btnActionPerformed(evt);
            }
        });

        point_btn.setText(".");
        point_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                point_btnActionPerformed(evt);
            }
        });

        ans_btn.setText("=");
        ans_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_btnActionPerformed(evt);
            }
        });

        i0_btn.setText("0");
        i0_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i0_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_text)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i1_btn)
                            .addComponent(i7_btn)
                            .addComponent(i4_btn)
                            .addComponent(c_btn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel_btn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i2_btn)
                                    .addComponent(i8_btn)
                                    .addComponent(i5_btn)
                                    .addComponent(i0_btn))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i3_btn)
                            .addComponent(i9_btn)
                            .addComponent(i6_btn)
                            .addComponent(per_btn)
                            .addComponent(point_btn))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_btn)
                            .addComponent(mul_btn)
                            .addComponent(sub_btn)
                            .addComponent(dev_btn)
                            .addComponent(ans_btn))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(input_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c_btn)
                                .addGap(38, 38, 38)
                                .addComponent(i7_btn)
                                .addGap(18, 18, 18)
                                .addComponent(i4_btn)
                                .addGap(29, 29, 29)
                                .addComponent(i1_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(per_btn)
                                .addGap(38, 38, 38)
                                .addComponent(i9_btn)
                                .addGap(18, 18, 18)
                                .addComponent(i6_btn)
                                .addGap(29, 29, 29)
                                .addComponent(i3_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dev_btn)
                                .addGap(38, 38, 38)
                                .addComponent(mul_btn)
                                .addGap(18, 18, 18)
                                .addComponent(sub_btn)
                                .addGap(29, 29, 29)
                                .addComponent(add_btn)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(point_btn)
                            .addComponent(ans_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_btn)
                        .addGap(38, 38, 38)
                        .addComponent(i8_btn)
                        .addGap(18, 18, 18)
                        .addComponent(i5_btn)
                        .addGap(29, 29, 29)
                        .addComponent(i2_btn)
                        .addGap(18, 18, 18)
                        .addComponent(i0_btn)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i9_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i9_btnActionPerformed
        String number1 = input_text.getText() + i9_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i9_btnActionPerformed

    private void ans_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_btnActionPerformed
        String number2 = input_text.getText();
        n2 = Double.parseDouble(number2);
        
        if (operator == "+")
        {
            result = n1 + n2;
            
            input_text.setText(String.valueOf(result));
        }
        else if (operator == "-") {
            result = n1 - n2;
            
            input_text.setText(String.valueOf(result));
        }else if (operator == "/") {
            result = n1 / n2;
            
            input_text.setText(String.valueOf(result));
        }else if (operator == "*") {
            result = n1 * n2;
            
            input_text.setText(String.valueOf(result));
        }else if (operator == "%") {
            result = n1 % n2;
            
            input_text.setText(String.valueOf(result));
        }
        
    }//GEN-LAST:event_ans_btnActionPerformed

    private void i7_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i7_btnActionPerformed
       String number1 = input_text.getText() + i7_btn.getText();
       input_text.setText(number1);
       
    }//GEN-LAST:event_i7_btnActionPerformed

    private void i8_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i8_btnActionPerformed
        String number1 = input_text.getText() + i8_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i8_btnActionPerformed

    private void i4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i4_btnActionPerformed
        String number1 = input_text.getText() + i4_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i4_btnActionPerformed

    private void i5_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i5_btnActionPerformed
       String number1 = input_text.getText() + i5_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i5_btnActionPerformed

    private void i6_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i6_btnActionPerformed
        String number1 = input_text.getText() + i6_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i6_btnActionPerformed

    private void i1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1_btnActionPerformed
        String number1 = input_text.getText() + i1_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i1_btnActionPerformed

    private void i2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2_btnActionPerformed
        String number1 = input_text.getText() + i2_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i2_btnActionPerformed

    private void i3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3_btnActionPerformed
        String number1 = input_text.getText() + i3_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i3_btnActionPerformed

    private void i0_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i0_btnActionPerformed
        String number1 = input_text.getText() + i0_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_i0_btnActionPerformed

    private void point_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_point_btnActionPerformed
        String number1 = input_text.getText() + point_btn.getText();
       input_text.setText(number1);
    }//GEN-LAST:event_point_btnActionPerformed

    private void c_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_btnActionPerformed
       input_text.setText("");
    }//GEN-LAST:event_c_btnActionPerformed

    private void mul_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul_btnActionPerformed
       n1 = Double.parseDouble(input_text.getText());
       input_text.setText("");
       operator = "*";
       
    }//GEN-LAST:event_mul_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
        n1 = Double.parseDouble(input_text.getText());
       input_text.setText("");
       operator = "-";
    }//GEN-LAST:event_sub_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
       n1 = Double.parseDouble(input_text.getText());
       input_text.setText("");
       operator = "+";
    }//GEN-LAST:event_add_btnActionPerformed

    private void dev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dev_btnActionPerformed
        n1 = Double.parseDouble(input_text.getText());
       input_text.setText("");
       operator = "/";
    }//GEN-LAST:event_dev_btnActionPerformed

    private void per_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_per_btnActionPerformed
        n1 = Double.parseDouble(input_text.getText());
       input_text.setText("");
       operator = "%";
    }//GEN-LAST:event_per_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        input_text.setText(input_text.getText().substring(0, input_text.getText ().length() - 1));
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton ans_btn;
    private javax.swing.JButton c_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton dev_btn;
    private javax.swing.JButton i0_btn;
    private javax.swing.JButton i1_btn;
    private javax.swing.JButton i2_btn;
    private javax.swing.JButton i3_btn;
    private javax.swing.JButton i4_btn;
    private javax.swing.JButton i5_btn;
    private javax.swing.JButton i6_btn;
    private javax.swing.JButton i7_btn;
    private javax.swing.JButton i8_btn;
    private javax.swing.JButton i9_btn;
    private javax.swing.JTextField input_text;
    private javax.swing.JButton mul_btn;
    private javax.swing.JButton per_btn;
    private javax.swing.JButton point_btn;
    private javax.swing.JButton sub_btn;
    // End of variables declaration//GEN-END:variables
}
